name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Set up JDK environment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Build the app
        run: ./gradlew build