name: Wkwk
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Test the app
        run: |
          ./gradlew testDebugUnitTest
          ./gradlew createDebugCoverageReport
        uses: codecov/codecov-action@v1
        with:
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)

